### ISSUE TITLE
dropdown-item border if latest is hidden

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/design-system#165]
## Quick summary of bug

Today the CSS is 
```css
.dropDown-item:last-of-type {
  border-bottom: 0;
}

.dropDown-item {
  border-bottom: 1px solid #dde6ec;
}
```

It works well BUT if we hide the latest `.dropDown-item` as `.dropDown-item:last-of-type` doesn't care if the item is visible or not we see the border-bottom :/ 

## Actual Behavior

![Screenshot from 2019-07-03 17-20-43](https://user-images.githubusercontent.com/713283/60603900-e69a6e80-9db6-11e9-97a7-dd27e3c79f67.png)

## Expected Behavior

![Screenshot from 2019-07-03 17-20-09](https://user-images.githubusercontent.com/713283/60603908-eb5f2280-9db6-11e9-8b67-7ee9c0a8e40d.png)

## Steps to Reproduce the Problem

  1. Open a dropdown with items
  2. Hide the latest one 
  3. :popcorn: 

## Possible fixes

Using `+` fix the issue

```css 
.dropDown-item + .dropDown-item {
  border-top: 1px solid #dde6ec;
}
```
