### ISSUE TITLE
Document square helper !

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/design-system#167]
## Feature description

DOCUMENT. ALWAYS. DON'T DISCUSS.

```css
[class*="ratio-container-"] {
  width: 100%;
  height: 0;
  @extend .relative;
}
.ratio-container-square {
  padding-top: 100%;
}
.ratio-container-16-9 {
  padding-top: 56.25%;
}

.inner-ratio-container {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```

## Benefits (optional)

DOCUMENT. ALWAYS. DON'T DISCUSS.
